### ISSUE TITLE
Available races are not shown on start

### ISSUE THREAD

**Issue by ppraisethesun** [oestrich/ex_venture#12]
Can't see available races after entering name

![image](https://user-images.githubusercontent.com/18067021/35837849-22b49e7a-0b34-11e8-8b26-2a15f062801b.png)

**Comment by oestrich** [comment]
Did you run the seeds? The races that are listed should be whatever races are created in the database.

**Comment by ppraisethesun** [comment]
Oh, yes, i only ran ecto.create and ecto.migrate, sorry

**Comment by oestrich** [comment]
No worries, I'm just happy it was simple
