### ISSUE TITLE
New account gives "can't be blank" for filled-in password

### ISSUE THREAD

**Issue by nomicflux** [oestrich/ex_venture#124]
Immediately after initial setup and running `mix run --no-halt`, going to http://localhost:4000/register, filling out all fields (except for email), and clicking on "Create Your Account", the message "can't be blank" appears below the password field:

![image](https://user-images.githubusercontent.com/13767188/52181406-03eef080-27b7-11e9-94cd-d4b631b8706b.png)

**Comment by nomicflux** [comment]
This appears to be related to hashing; changing the line
```eex
        <%= error_tag f, :password_hash %>
```
to
```eex
        <%= error_tag f, :password %>
```

in web/templates/registration/new.html.eex allows the account to be created after fixing other validation errors.

**Comment by oestrich** [comment]
Hmm, I was able to make an account locally without issue. Did your passwords match? It might be that along with what you just found.

**Comment by oestrich** [comment]
Yeah I'm not sure. Might be worth switching the password field to using `error_tag(f, :password)`. Might be some other small tweaks that need to happen but this is a good start.
