### ISSUE TITLE
Trying again to install via docker

### ISSUE THREAD

**Issue by shifters67** [oestrich/ex_venture#135]
HI,

trying to install via docker instructions on the project website.

When i try and login via website it says there was a problem creating the account and account creation failed contact the administrator.  When i try via tintin i get a url to connect to https:/connection/authorize?id=9f439079-b394-4cb9-b1c0-59351a2b5b5f

i assume connection should be 127.0.0.1:4000 as its run locally?

When you try and connect you get an ssl error:

An error occurred during a connection to 127.0.0.1:4000. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG 

This is using the latest firefox if thats relevant. And latest docker and docker-compose.

Can any one help?

thanks!

shifters

**Comment by shifters67** [comment]
no response to basic question

**Comment by oestrich** [comment]
Hey, sorry for the late response, but I don't actually know what's wrong with the docker build. It's most likely very out of date and missing some config. If you're looking to get a build going I'd definitely run it outside of docker as I know that works. Someone else got the docker compose stuff working a while ago and I didn't really keep up to date with it as I don't use docker for developing. If you get it working I'd love to review a PR though!

I'd you want more real time help I'm usually available in the exventure discord.

**Comment by shifters67** [comment]
Ah thanks for the response!

I thought the docker image was an official project release and hence was surprised when it didnt run.  The docker image is a great way of doing it as it encapsulates all the software requirements.  Can you put a warning on the web page as it is a shame to be put off using it thinking the builds a re broken!

I do read the project progress on the elixir weekly newsletters with interest.

thanks

shifters

**Comment by oestrich** [comment]
I think I got it going again? It at least loaded for me. I bumped the base docker image to 1.8-alpine and it seems to be working. Let me know if it does for you.

**Comment by shifters67** [comment]
Thanks it does indeed work now!

shifters
