### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by Preciousring** [oestrich/ex_venture#32]
When attempting to run ecto.migrate on a cloud sql server, i had an error saying that ``"update users set save = (select row_to_json(t) from (select id as room_id from rooms limit 1) t)`` is a json expression while save is a jsonb column. I had to cast the expression to jsonb in order to continue.

I had also another error with uuid, i have changed the sql request ``create extension \"uuid-ossp\";`` to `create extension IF NOT EXISTS \"uuid-ossp\";`

**Comment by oestrich** [comment]
The extension issue is fixed on master. My guess is the server already prefilled contrib extensions for you.

Can you try to replace `row_to_json` with `to_jsonb` and see if that fixes it on the cloud server?

**Comment by Preciousring** [comment]
When i encountered this error, i changed ``execute "update users set save = (select row_to_json(t) from (select id as room_id from rooms limit 1) t);"`` to `execute "update users set save = (select row_to_json(t) from (select id as room_id from rooms limit 1) t)::jsonb;"` if i remember correctly. I've done an ugly cast and it worked. But i'm following your advice, since the cloud hosting company uses a deprecated version of PostgreSQL, i've changed to AWS for the database.

**Comment by oestrich** [comment]
I switched the user save migration to use `to_jsonb` since it seems to do the same thing. If you still have any issues I can reopen this. Hopefully AWS PG works better!
