### ISSUE TITLE
Player already in room upon entering

### ISSUE THREAD

**Issue by vadi2** [oestrich/ex_venture#51]
When I enter a room, it says that my character is already there.

**Comment by vadi2** [comment]
This feels off, the normal expectation it to see everybody but me.

**Comment by oestrich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Do not show yourself in the room list](https://trello.com/c/TlnvnGi4/193-do-not-show-yourself-in-the-room-list)

**Comment by oestrich** [comment]
Closed with 003392c
