### ISSUE TITLE
Wrong target still attacks current target

### ISSUE THREAD

**Issue by vadi2** [oestrich/ex_venture#52]
https://ada-young.appspot.com/pastebin/Jxyv9DOe

This seems dangerous and a potential source of frustration if the engine auto-picks to do something else than what you intended. I think it should complain about the invalid attack order.

While it seems like a convenience, there could be a situation where you make a mistake and didn't mean to attack, for example, and the engine finding a valid target and aggroing it for you would be bad.

**Comment by oestrich** [comment]
This is a newer convenience that got bugged I think. I definitely agree that if you add a target for the skill it should say "Sorry not found" instead of passing through to your current target (which was auto set because they targeted you and you had no target)
