### ISSUE TITLE
Stats/boost gives error when saving

### ISSUE THREAD

**Issue by thedandroid** [oestrich/ex_venture#80]
When trying to add the stats/boost effect to a skill and edit any field it errors when saving. "There was an issue update [skill]. Please try again."

It works if you leave the default values, but any changes will cause it to not save.

**Comment by oestrich** [comment]
Fixed in bcf820dc36cce3499408569be3fe1e3134bfb74b

I believe the issue was improperly parsing the fields so they were strings in the backend, and that was failing validation.
