### ISSUE TITLE
Problem with docker set up

### ISSUE THREAD

**Issue by shifters67** [oestrich/ex_venture#86]
Hi,

I get the following on Ubuntu 18.04

~/Dev/ex_venture-master$ docker-compose run --rm ex_venture seed
Starting ex_venture-master_postgres_1 ... done
Loading ex_venture...
Starting dependencies..
Starting repos..
Running seed script..
▸  Evaluation failed with: ERROR 42P01 (undefined_table): relation "zones" does not exist

This is from following the instructions here: https://exventure.org/docker/

I have installed:
  Docker version 18.06.1-ce, build e68fc7a and docker-compose version 1.21.2, build a133471

Any ideas?  This was pulled from github on the 28th September

Thanks

Tom

**Comment by oestrich** [comment]
Closing due to age. If this is still an issue let me know
